version: '3.8'
services:
  app:
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bus_station
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 16072001
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
